In [ ]:
import pandas as pd

In [ ]:
bdf = pd.read_csv("./Dataset/datasets/bad_daraz_dataset.csv")

In [ ]:
bdf.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               2
seller              0
city                0
brand               0
gender_target       0
age                 2
reviews             0
dtype: int64

In [ ]:
bdf.fillna(0) # filling na with 0

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,0.0,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,0,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,0,90
9,9,Cup,Electronics,1800,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,0,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [ ]:
bdf["price"] = pd.to_numeric(bdf["price"], errors  = "coerce")

In [ ]:
bdf["price"]=bdf["price"].fillna(bdf["price"].mean())

In [ ]:
bdf["age"]

0          25
1          30
2          22
3      Female
4          28
5         24
6          25
7          19
8         NaN
9         NaN
10         21
11         26
12    Unknown
13    Unknown
Name: age, dtype: str

In [ ]:
bdf["age"] = pd.to_numeric(bdf["age"], errors = "coerce")

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,NaN,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,NaN,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,NaN,44

In [ ]:
bdf["age"] = bdf["age"].fillna(bdf["age"].median())

In [ ]:
bdf.dropna()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf[bdf.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        14 non-null     int64
 1   product_name      14 non-null     str
 2   category          14 non-null     str
 3   price             14 non-null     float64
 4   discount_percent  13 non-null     str
 5   rating            13 non-null     float64
 6   stock             12 non-null     str
 7   seller            14 non-null     str
 8   city              14 non-null     str
 9   brand             14 non-null     str
 10  gender_target     14 non-null     str
 11  age               14 non-null     float64
 12  reviews           14 non-null     int64
dtypes: float64(3), int64(2), str(8)
memory usage: 1.6 KB

In [ ]:
bdf.head()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
# completely match ---> complete duplication
# partial match ---> Partial duplication

In [ ]:
# dupliated method
bdf.duplicated()
# 12th index is comlplete duplicate 12     True
# 1 and 7th index is partial duplicate

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
dtype: bool

In [ ]:
bdf[bdf.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf.duplicated("product_id") # checking product_id duplications

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
dtype: bool

In [ ]:
bdf.drop_duplicates() # dropped all the duplicates

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
# Complete duplication data are removed and updated the datasets
bdf.drop_duplicates(inplace = True)

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
# removing partial duplication
bdf.drop_duplicates(subset = "product_id")

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
# Complete duplication data are removed and updated the datasets

bdf.drop_duplicates(subset = "product_id", inplace = True)

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf[bdf["price"] < 0]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf[bdf["rating"] > 5]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
11,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12

In [ ]:
bdf.loc[bdf["price"] < 0,"price"] = bdf["price"].mean()

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,16255.555556,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
bdf['stock'] = pd.to_numeric(bdf['stock'],errors = 'coerce')

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,NaN,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,Janakpur,Generic,Unisex,26.0,12
12,12,Chair,Furniture,16255.555556,10,4.0,-5.0,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [ ]:
# drop stock that is less than 0, stock cannot be negative
bdf = bdf[bdf['stock'] > 0]

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,Biratnagar,Adidas,Female,25.0,30
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,Dharan,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,Janakpur,Generic,Unisex,26.0,12

In [ ]:
bdf['city']

0       Kathmandu
1         Pokhara
2         Itahari
3      Biratnagar
5         Pokhara
6       Kathmandu
7          Dharan
10     Kathmandu
11       Janakpur
Name: city, dtype: str

In [ ]:
# inconsistence kathmandu

bdf['city']=bdf['city'].str.strip()

# str.lstrip() removes the left whitespaces
# str.rstrip() removes the right whitespaces

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,Biratnagar,Adidas,Female,25.0,30
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,Dharan,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,Janakpur,Generic,Unisex,26.0,12

In [ ]:
bdf['city'] = bdf['city'].str.upper() # UPPER case

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,KATHMANDU,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,POKHARA,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,ITAHARI,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,BIRATNAGAR,Adidas,Female,25.0,30
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,POKHARA,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,KATHMANDU,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,DHARAN,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,KATHMANDU,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,JANAKPUR,Generic,Unisex,26.0,12

In [ ]:
bdf['city'] = bdf['city'].str.lower() #lower case

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,biratnagar,Adidas,Female,25.0,30
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,dharan,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,janakpur,Generic,Unisex,26.0,12

In [ ]:
bdf['city']=bdf['city'].str.title() # First caracter capital and  remaining small letter

In [ ]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,13883.333333,15,4.6,40.0,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60.0,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150.0,Style,Biratnagar,Adidas,Female,25.0,30
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75.0,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25.0,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,13883.333333,12,3.9,45.0,CarryAll,Dharan,Wildcraft,Female,19.0,18
10,10,Keyboard,Electronics,2500.000000,5,4.4,35.0,TechHub,Kathmandu,Logitech,Unisex,21.0,110
11,11,Bottle,Home,800.000000,0,5.5,100.0,HomeStore,Janakpur,Generic,Unisex,26.0,12

In [ ]:
# Outliers
    # that kinda value which lies beyond the actual valuehai haina

# salary = 10000, 20000, 30000, 40000, 100000
    # here 100000 is beyond the salary  which can be treated as outlier

# salary1 = 10000, 20000, 30000, 40000, -100000
    # here -100000 is the salary  which is invalid / incorrect

# IQR method
# Interquartile range
# Detect outliers
# Q1 = df["salary"].quartiles(0.25)
# Q3 = df["salary"].quartiles(0.75

# IQR = Q3 - Q1
#     = 10000 -  4000
#     = 6000

        # measures spread of the middle 50% of the data
# lower = Q1 - 1.5 * IQR = 4000 - 1.5 *  6000 = -5000
# upper = Q1 + 1.5 * IQR = 10000 + 1.5 * 6000 = 19000