In [36]:
import pandas as pd

In [37]:
df = pd.DataFrame({
    "Salary": [1000,2000,3000,4000,5000,6000,100000]
})

In [38]:
df

   Salary
0    1000
1    2000
2    3000
3    4000
4    5000
5    6000
6  100000

In [39]:
q1 = df["Salary"].quantile(0.25)
q1

np.float64(2500.0)

In [40]:
q2 = df["Salary"].mean()
q2

np.float64(17285.714285714286)

In [41]:
q3 = df["Salary"].quantile(0.75)
q3

np.float64(5500.0)

In [42]:
iqr = q3 - q1
iqr

np.float64(3000.0)

In [43]:
lower_bound = q1 - 1.5 * iqr
lower_bound

np.float64(-2000.0)

In [44]:
upper_bound = q3 + 1.5 * iqr
upper_bound

np.float64(10000.0)

In [45]:
outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
outliers

   Salary
6  100000

In [46]:
ddf = pd.read_csv("bad_daraz_dataset.csv")

In [47]:
ddf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [48]:
# Replacing price data to numeric
ddf["price"] = pd.to_numeric(ddf["price"],errors = "coerce")

In [49]:
ddf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [50]:
# Outlier detcting

# Quartile Q3, Q1 and iqr

In [51]:
q1 = ddf["price"].quantile(0.25)
q1

np.float64(1575.0)

In [52]:
q2 = ddf["price"].quantile(0.50)
q2

np.float64(3000.0)

In [53]:
q3 = ddf["price"].quantile(0.75)
q3

np.float64(5175.0)

In [54]:
iqr = q3 - q1
iqr

np.float64(3600.0)

In [55]:
lower_bound = q1 - 1.5 * iqr
lower_bound

np.float64(-3825.0)

In [56]:
upper_bound = q3 + 1.5 * iqr
upper_bound

np.float64(10575.0)

In [57]:
outliers = ddf[(ddf["price"] < lower_bound) | (ddf["price"] > upper_bound)]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120

In [58]:
median = ddf["price"].median()
median

np.float64(3000.0)

In [62]:
# Replace outlier by median

# ddf.loc[(ddf["price"] < lower_bound) | (ddf["price"] > upper_bound),"price"] = median
# ddf

In [63]:
len(outliers)

2

In [66]:
# detected outlier change into lower_bound or upper_bound
    # Since the detected value (75000.0) is greater than the upper_bound (10575.0) 
    # We gotta change it to upper_bound value i.e 10575.0
# here the clip() method to fix the outliers

ddf["price"]=ddf["price"].clip(lower_bound,upper_bound)

In [68]:
ddf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,10575.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,10575.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [69]:
# clipping / capping

In [ ]:
# Z-Score Method
# standard deviation

In [70]:
ddf["price"].std()

np.float64(4144.487637546742)

In [ ]:
47:54