In [1]:
import pandas as pd
bdf = pd.read_csv("./Dataset/datasets/bad_daraz_dataset.csv")

In [2]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [3]:
bdf.head()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80

In [4]:
bdf.isnull()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
bdf.columns

Index(['product_id', 'product_name', 'category', 'price', 'discount_percent',
       'rating', 'stock', 'seller', 'city', 'brand', 'gender_target', 'age',
       'reviews'],
      dtype='str')

In [6]:
bdf.shape

(13, 13)

In [7]:
bdf.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64

In [8]:
# Detect the dirty data
# Missing values (nan,duplicate,wrong dataType, negative Pricing,  etc. )
# Catching outliers
# Inconsistency (kathMANDU,KATHMANDU,kathmandu)
#

In [9]:
bdf.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64

In [10]:
bdf.fillna(0) # filling na with 0

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,0.0,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,0,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,0,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [11]:
# bdf["price"].fillna(bdf["price"].mean())

In [12]:
dummy = pd.Series(["100","200","300"])
dummy

0    100
1    200
2    300
dtype: str

In [13]:
pd.to_numeric(dummy)

0    100
1    200
2    300
dtype: int64

In [14]:
dumb = pd.Series(["100","a","300"])
dumb

0    100
1      a
2    300
dtype: str

In [15]:
# ValueError: Unable to parse string "a" at position 1

# pd.to_numeric(dumb)

In [16]:
pd.to_numeric(dumb,errors = "coerce")

0    100.0
1      NaN
2    300.0
dtype: float64

In [17]:
# changing dType of price To numeric and errors  = "coerce" NaN

bdf["price"] = pd.to_numeric(bdf["price"], errors  = "coerce")

bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [18]:
bdf["price"]=bdf["price"].fillna(bdf["price"].mean())

In [19]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [20]:
bdf["age"]

0          25
1          30
2          22
3      Female
4          28
5         24
6          25
7          19
8         NaN
9          21
10         26
11    Unknown
12    Unknown
Name: age, dtype: str

In [21]:
bdf["age"] = pd.to_numeric(bdf["age"], errors = "coerce")

In [22]:
bdf["age"]

0     25.0
1     30.0
2     22.0
3      NaN
4     28.0
5     24.0
6     25.0
7     19.0
8      NaN
9     21.0
10    26.0
11     NaN
12     NaN
Name: age, dtype: float64

In [23]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,NaN,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,NaN,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,NaN,44

In [24]:
bdf["age"] = bdf["age"].fillna(bdf["age"].median())

In [25]:
bdf["age"]

0     25.0
1     30.0
2     22.0
3     25.0
4     28.0
5     24.0
6     25.0
7     19.0
8     25.0
9     21.0
10    26.0
11    25.0
12    25.0
Name: age, dtype: float64

In [26]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [27]:
bdf.dropna()

bdf[bdf.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [28]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [29]:
bdf.dropna()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [30]:
bdf.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
dtype: bool

In [31]:
bdf[bdf.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [32]:
bdf.discount_percent

0      10
1      15
2      5%
3      20
4      10
5     NaN
6      10
7      12
8       5
9       5
10      0
11     10
12     10
Name: discount_percent, dtype: str

In [33]:
bdf["discount_percent"] = bdf["discount_percent"].str.replace("%","")

In [34]:
bdf.discount_percent

0      10
1      15
2       5
3      20
4      10
5     NaN
6      10
7      12
8       5
9       5
10      0
11     10
12     10
Name: discount_percent, dtype: str

In [35]:
bdf["discount_percentage"] = bdf["discount_percent"].str.replace("%","")
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percentage
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.000000,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,NaN
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [36]:
bdf.fillna(0) # filling na with 0

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percentage
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.000000,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.000000,20,0.0,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.000000,0,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,0
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.000000,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [37]:
bdf[bdf.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percentage
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [38]:
bdf.drop_duplicates(inplace=True)

In [39]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percentage
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.000000,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,NaN
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10

In [40]:
bdf.fillna(0) # filling na with 0

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews,discount_percentage
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
1,2,Phone,Electronics,14981.818182,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210,15
2,3,Shoes,Fashion,3500.000000,5,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55,5
3,4,T-Shirt,Fashion,1500.000000,20,0.0,150,Style,Biratnagar,Adidas,Female,25.0,30,20
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80,10
5,6,Headphones,Electronics,4200.000000,0,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65,0
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120,10
7,8,Bag,Fashion,14981.818182,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18,12
8,9,Mouse,Electronics,1800.000000,5,4.3,0,TechHub,Kathmandu,Logitech,Unisex,25.0,90,5
9,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110,5
10,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12,0
11,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44,10