In [13]:
import pandas as pd
bdf = pd.read_csv("./Dataset/datasets/bad_daraz_dataset.csv")

In [14]:
bdf

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [15]:
bdf.head()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80

In [16]:
bdf.isnull()

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,True,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
bdf.columns

Index(['product_id', 'product_name', 'category', 'price', 'discount_percent',
       'rating', 'stock', 'seller', 'city', 'brand', 'gender_target', 'age',
       'reviews'],
      dtype='str')

In [18]:
bdf.shape

(12, 13)

In [19]:
bdf.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64

In [ ]:
# Detect the dirty data
# Missing values (nan,duplicate,wrong dataType, negative Pricing,  etc. )
# Catching outliers
# Inconsistency (kathMANDU,KATHMANDU,kathmandu)
#

In [21]:
bdf.isnull().sum()

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               1
seller              0
city                0
brand               0
gender_target       0
age                 1
reviews             0
dtype: int64