In [2]:
# 1. Series         --> 1d data type
# 2. DataFrames     --> 2d data type
# 
# Datasets --> Collection of data
    # Internal datasets
    # External datasets

In [3]:
import pandas as pd

In [4]:
result = pd.Series(["Japan", "Austria", "China", "Nepal"])
print(result)

0      Japan
1    Austria
2      China
3      Nepal
dtype: str

In [5]:
number_series = pd.Series([10,20,30,40],  index = ["ek", "dwe", "tin", "char"])
print(number_series)

ek      10
dwe     20
tin     30
char    40
dtype: int64

In [ ]:
# NOTE:

# pd            --> pandas
# pd.Series()   --> Method
# [10,20,30,40] --> 1st Argument
# index = ["ek", "dwe", "tin", "char"] --> 2nd Argument

In [ ]:
# A collection of series is  known as dataframe

In [8]:
# Creating a Dictionary
student_data = {
    "Name" : ["Surya","Loyas","Nilas"],
    "Age" : [20,26,30],
    "Location" : ["ktm","atm","ptn"],
    "Course" : ["Python","sql","Mern"]
}

# Creating dataframe
student_dataframe =  pd.DataFrame(student_data)
print(student_dataframe)

    Name  Age Location  Course
0  Surya   20      ktm  Python
1  Loyas   26      atm     sql
2  Nilas   30      ptn    Mern

In [9]:
df = pd.read_json("students_data.json")

In [10]:
df

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
0,1,Sabina Pandey,19,Male,9866879003,sabina.pandey1@gmail.com,Dharan,Sunsari,Koshi,"[NodeJS, C++]",17394,1532,60,84,AI Udaan Day,2026-07-26,True,False
1,2,Sujan Poudel,28,Male,9870676580,sujan.poudel2@gmail.com,Nepalgunj,Banke,Lumbini,[Flutter],46200,3006,75,78,Evening,2026-12-02,True,False
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Asmita Rai,27,Female,9836813605,asmita.rai496@gmail.com,Pokhara,Kaski,Gandaki,"[Figma, Power BI, MERN]",36254,4325,89,58,Weekend,2026-05-12,True,False
496,497,Ramesh Joshi,28,Male,9826553259,ramesh.joshi497@gmail.com,Chitwan,Chitwan,Bagmati,"[Power BI, Digital Marketing, MERN]",29738,2434,96,86,Evening,2026-11-06,True,False
497,498,Sabina Khadka,25,Male,9820772678,sabina.khadka498@gmail.com,Janakpur,Dhanusha,Madhesh,"[C++, Digital Marketing, Excel, Power BI]",16298,2316,81,85,Evening,2026-07-15,True,False
498,499,Rohan Acharya,30,Female,9833337211,rohan.acharya499@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Digital Marketing]",37942,1242,73,65,Evening,2026-01-09,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [11]:
df.head()

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
0,1,Sabina Pandey,19,Male,9866879003,sabina.pandey1@gmail.com,Dharan,Sunsari,Koshi,"[NodeJS, C++]",17394,1532,60,84,AI Udaan Day,2026-07-26,True,False
1,2,Sujan Poudel,28,Male,9870676580,sujan.poudel2@gmail.com,Nepalgunj,Banke,Lumbini,[Flutter],46200,3006,75,78,Evening,2026-12-02,True,False
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False