In [1]:
import pandas as pd
import numpy as np
# Scalar

x = 10
y = 20
# x and y has a single value and is called scalar.

age = 29
roll_no = 2

# age and roroll_no has a single value and is called scalar.

In [2]:
age  = [20]

In [3]:
# Vector

# A collection of scalar is called a vector
# eg.
# age = np.array([1, 2, 3, 4, 5])
    # Note: list of scalar values is called vector.

In [4]:
ages = [20,30,40,38,33]
age_vector = pd.Series(ages)

In [5]:
age_vector

0    20
1    30
2    40
3    38
4    33
dtype: int64

In [6]:
pd.DataFrame(age_vector)

    0
0  20
1  30
2  40
3  38
4  33

In [7]:
df = pd.read_csv("daraz_dataset.csv")

In [8]:
df.head()

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled

In [9]:
# in mathematics it is called vector
age = np.array([10,20,30,40])
print(age)

roll_no = np.array([20,21,22,23])
print(roll_no)

# we got 2 vector from above data
# i.e 
# [10 20 30 40]
# [20 21 22 23]

[10 20 30 40]
[20 21 22 23]

In [10]:
# vector + vector chahi matrix   huncha

# ie.
vdf = np.array([
    [1,2,3],
    [4,5,6]
])
print(vdf)
# it is a matrix, a collection of vectors

[[1 2 3]
 [4 5 6]]

In [11]:
vdf.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
st_data = np.array([12,90])
weight = np.array([10,2])

prediction = np.dot(st_data, weight)
prediction

np.int64(300)

In [13]:
st_data = np.array([12,90,18,200,30])
weight = np.array([10,2,2,4,3])
prediction = np.dot(st_data, weight)
prediction

np.int64(1226)

In [14]:
st_data = np.array([
    [12,90,18,200,30],
    [1,2,3,4,5],
    [23,23,43,3,43]
])
s_hrs = np.array([
    [10,2,2,4,3],
    [1,2,3,4,5],
    [5,4,3,2,1]
])

weight = np.array([
    [10],
    [2],
    [3],
    [34],
    [3]
])
print(st_data)

prediction = np.dot(st_data, weight)
print(prediction)

[[ 12  90  18 200  30]
 [  1   2   3   4   5]
 [ 23  23  43   3  43]]
[[7244]
 [ 174]
 [ 636]]

In [15]:
a = np.array([
    [12,90],
    [14,80],
    [16,50]
    ])

weight = np.array([
    [10],
    [2]
])
prediction = np.dot(a, weight)
print(prediction)

[[300]
 [300]
 [260]]

In [ ]:
# vector * vector ==  dot product
# matrix * matrix == matrix product