In [25]:
import pandas as pd

In [26]:
df = pd.read_csv('bad_daraz_dataset.csv')

In [27]:
df

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [28]:
df.category

0     Electronics
1     Electronics
2         Fashion
3         Fashion
4     Accessories
5     Electronics
6     Electronics
7         Fashion
8     Electronics
9     Electronics
10           Home
11      Furniture
Name: category, dtype: str

In [29]:
# grouping data

df.groupby("category")

In [30]:
# loop iteration of group

# when we pass the print(data), it excecutes all the groups
for category,data in df.groupby("category"):
    # print(category)
    print(data)

   product_id product_name     category price discount_percent  rating  \
4           5        Watch  Accessories  5500               10     4.5

          stock seller       city  brand gender_target age  reviews
4  Out of Stock  TimeX  Kathmandu  Casio          Male  28       80
   product_id product_name     category  price discount_percent  rating stock  \
0           1       Laptop  Electronics  75000               10     4.8    25
1           2        Phone  Electronics    NaN               15     4.6    40
5           6   Headphones  Electronics   4200              NaN     4.1    75
6           7       Laptop  Electronics  75000               10     4.8    25
8           9        Mouse  Electronics   1800                5     4.3   NaN
9          10     Keyboard  Electronics   2500                5     4.4    35

        seller         city     brand gender_target   age  reviews
0      TechHub    Kathmandu      Dell        Unisex    25      120
1  GadgetNepal      Pokhara   Samsung        Unisex    30      210
5     AudioPro      Pokhara       JBL        Unisex   24        65
6      TechHub    Kathmandu      Dell        Unisex    25      120
8      TechHub    Kathmandu  Logitech        Unisex   NaN       90
9     TechHub    Kathmandu   Logitech        Unisex    21      110
   product_id product_name category price discount_percent  rating stock  \
2           3        Shoes  Fashion  3500               5%     4.2    60
3           4      T-Shirt  Fashion  1500               20     NaN   150
7           8          Bag  Fashion   abc               12     3.9    45

       seller        city      brand gender_target     age  reviews
2  FashionHub     Itahari       Nike          Male      22       55
3       Style  Biratnagar     Adidas        Female  Female       30
7    CarryAll      Dharan  Wildcraft        Female      19       18
    product_id product_name   category  price discount_percent  rating stock  \
11          12        Chair  Furniture  -2500               10     4.0    -5

     seller      city brand gender_target      age  reviews
11  FurniCo  Lalitpur  IKEA        Unisex  Unknown       44
    product_id product_name category price discount_percent  rating stock  \
10          11       Bottle     Home   800                0     5.5   100

       seller      city    brand gender_target age  reviews
10  HomeStore  Janakpur  Generic        Unisex  26       12

In [31]:
# group the Electronics in separate form
# get group method to get the group of data

Electronics = df.groupby("category").get_group("Electronics")
Electronics

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110

In [32]:
# getting all the Fashion group items
 
Fashion = df.groupby("category").get_group("Fashion")
Fashion

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18

In [33]:
for city,data in df.groupby("city"):
    print(city)

 Kathmandu
Biratnagar
Dharan
Itahari
Janakpur
Kathmandu
Lalitpur
Pokhara

In [34]:
Kathmandu = df.groupby("city").get_group("Kathmandu")
Kathmandu

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90

In [35]:
# group is used to explore data
# group doesn't changes or updates the data
# group makes the data easiness to read
# group doesn't supports the caluculation parts

In [36]:
for city, data in df.groupby("city"):
    print(city)

 Kathmandu
Biratnagar
Dharan
Itahari
Janakpur
Kathmandu
Lalitpur
Pokhara

In [37]:
# Aggregation
    # numerical data (price, rating) -->? process --> summarization

In [38]:
# Let's see
df.groupby("category")

In [39]:
df.groupby("category")

In [40]:
df.groupby("category")["product_name"].count()

category
Accessories    1
Electronics    6
Fashion        3
Furniture      1
Home           1
Name: product_name, dtype: int64

In [41]:
df.groupby("category")["price"].max()

category
Accessories     5500
Electronics    75000
Fashion          abc
Furniture      -2500
Home             800
Name: price, dtype: str

In [42]:
# single aggregation
df.groupby("category")["price"].min()

category
Accessories     5500
Electronics     1800
Fashion         1500
Furniture      -2500
Home             800
Name: price, dtype: str

In [43]:
# Multi Aggregation

df.groupby("category")["price"].agg(["max", "min", "count"])

               max    min  count
category
Accessories   5500   5500      1
Electronics  75000   1800      5
Fashion        abc   1500      3
Furniture    -2500  -2500      1
Home           800    800      1

In [52]:
# cleaning the price column to numeric

df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [50]:
df.groupby("category").agg({
    "price" : "mean",
    "rating" : "min",
    "reviews" : sum
})

               price  rating  reviews
category
Accessories   5500.0     4.5       80
Electronics  31700.0     4.1      715
Fashion       2500.0     3.9      103
Furniture    -2500.0     4.0       44
Home           800.0     5.5       12

In [53]:
# Data Visualization
    # bar charts
    # line charts
    # pie charts
    # hiostogram
    # scatterplot
    # box plot (outlier detection)